name: Keep Streamlit App Alive

on:
  schedule:
    # Запуск в 07:00 и 19:00 UTC (10:00 и 22:00 по Москве)
    - cron: '0 7,19 * * *'
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://vat-calculator-mgt.streamlit.app/" --max-redirs 10 > /dev/null || true
          echo "Пинг успешно отправлен!"
