name: Keep Streamlit App Alive

on:
  schedule:
    # Запуск каждые 12 часов
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://vat-calculator-mgt.streamlit.app/" --max-redirs 10 > /dev/null || true
          echo "Пинг успешно отправлен!"
