name: Keep Streamlit App Alive

on:
  schedule:
    # Запуск каждые 3 дня в 09:00 UTC
    - cron: '0 9 */3 * *'
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://vat-calculator-mgt.streamlit.app/" --max-redirs 10 > /dev/null || true
          echo "Пинг успешно отправлен!"
